/*
 * Sunset Valley+ | Strafenkatalog
 *
 * Paragraphen = echte kalifornische Gesetze:
 *   CVC = California Vehicle Code, PC = Penal Code, HS = Health & Safety Code,
 *   USC = United States Code (Bundesrecht, Zuständigkeit USMS)
 * Klasse: I = Infraction (Ordnungswidrigkeit), M = Misdemeanor (Vergehen),
 *         F = Felony (Verbrechen)
 * fine   = Geldstrafe in $ (Server-Werte, frei anpassbar)
 * jail   = Hafteinheiten (HE) für das Gefängnis-Script
 * points = Punkte auf den Führerschein (DMV-Punktesystem, Richtwerte)
 * license = true -> Führerscheinentzug empfohlen
 */
window.SVP_CATALOG = [
  {
    id: 'traffic', icon: '🚦', name: 'Verkehrsverstöße (CVC)', items: [
      { code: 'CVC 22350',      title: 'Nicht angepasste Geschwindigkeit (Basic Speed Law)', cls: 'I', fine: 250,  jail: 0,  points: 1 },
      { code: 'CVC 22349(a)',   title: 'Überschreitung Höchstgeschwindigkeit (65 mph)',       cls: 'I', fine: 350,  jail: 0,  points: 1 },
      { code: 'CVC 22348(b)',   title: 'Geschwindigkeit über 100 mph',                       cls: 'I', fine: 1000, jail: 0,  points: 2, license: true },
      { code: 'CVC 22400(a)',   title: 'Behinderung durch zu langsames Fahren',              cls: 'I', fine: 150,  jail: 0,  points: 1 },
      { code: 'CVC 21453(a)',   title: 'Rotlichtverstoß',                                    cls: 'I', fine: 500,  jail: 0,  points: 1 },
      { code: 'CVC 22450(a)',   title: 'Stoppschild missachtet',                             cls: 'I', fine: 250,  jail: 0,  points: 1 },
      { code: 'CVC 21801(a)',   title: 'Vorfahrt beim Linksabbiegen missachtet',             cls: 'I', fine: 250,  jail: 0,  points: 1 },
      { code: 'CVC 21950(a)',   title: 'Vorrang von Fußgängern am Überweg missachtet',       cls: 'I', fine: 300,  jail: 0,  points: 1 },
      { code: 'CVC 21658(a)',   title: 'Fahrstreifen nicht eingehalten',                     cls: 'I', fine: 200,  jail: 0,  points: 1 },
      { code: 'CVC 22107',      title: 'Unsicherer Spurwechsel / ohne Blinker',              cls: 'I', fine: 200,  jail: 0,  points: 1 },
      { code: 'CVC 21651(b)',   title: 'Falschfahrer auf geteilter Schnellstraße',           cls: 'M', fine: 2000, jail: 10, points: 2, license: true },
      { code: 'CVC 21755',      title: 'Rechts überholen (unsicher)',                        cls: 'I', fine: 250,  jail: 0,  points: 1 },
      { code: 'CVC 23123.5',    title: 'Handy am Steuer',                                    cls: 'I', fine: 200,  jail: 0,  points: 0 },
      { code: 'CVC 27315(d)',   title: 'Nicht angeschnallt',                                 cls: 'I', fine: 150,  jail: 0,  points: 0 },
      { code: 'CVC 22500',      title: 'Halte-/Parkverbot',                                  cls: 'I', fine: 100,  jail: 0,  points: 0 },
      { code: 'CVC 21806(a)',   title: 'Einsatzfahrzeug keine Rettungsgasse / Vorrang',      cls: 'I', fine: 500,  jail: 0,  points: 1 },
      { code: 'CVC 21809(a)',   title: 'Move-Over-Gesetz missachtet (Einsatzstelle)',        cls: 'I', fine: 400,  jail: 0,  points: 0 },
      { code: 'CVC 2800(a)',    title: 'Anweisung eines Beamten missachtet',                 cls: 'M', fine: 750,  jail: 5,  points: 1 },
      { code: 'CVC 23103(a)',   title: 'Rücksichtsloses Fahren (Reckless Driving)',          cls: 'M', fine: 1500, jail: 10, points: 2 },
      { code: 'CVC 23109(a)',   title: 'Illegales Straßenrennen (Speed Contest)',            cls: 'M', fine: 2500, jail: 15, points: 2, license: true },
      { code: 'CVC 23109(c)',   title: 'Burnout / Exhibition of Speed',                      cls: 'M', fine: 1000, jail: 5,  points: 1 },
      { code: 'CVC 22106',      title: 'Unsicheres Anfahren / Ausparken',                    cls: 'I', fine: 150,  jail: 0,  points: 1 },
      { code: 'CVC 21460(a)',   title: 'Doppelte durchgezogene Linie überfahren',            cls: 'I', fine: 250,  jail: 0,  points: 1 },
      { code: 'CVC 22526(a)',   title: 'Kreuzung blockiert (Anti-Gridlock)',                 cls: 'I', fine: 200,  jail: 0,  points: 0 },
      { code: 'CVC 21200.5',    title: 'Fahrradfahren unter Alkohol-/Drogeneinfluss',        cls: 'M', fine: 250,  jail: 0,  points: 0 },
    ]
  },
  {
    id: 'vehicle', icon: '🚗', name: 'Fahrzeug & Dokumente (CVC)', items: [
      { code: 'CVC 12500(a)',   title: 'Fahren ohne Führerschein',                           cls: 'M', fine: 1000, jail: 5,  points: 1 },
      { code: 'CVC 12951(a)',   title: 'Führerschein nicht mitgeführt',                      cls: 'I', fine: 100,  jail: 0,  points: 0 },
      { code: 'CVC 14601.1(a)', title: 'Fahren trotz Führerscheinentzug',                    cls: 'M', fine: 2500, jail: 15, points: 2 },
      { code: 'CVC 4000(a)(1)', title: 'Fahrzeug nicht zugelassen',                          cls: 'I', fine: 300,  jail: 0,  points: 0 },
      { code: 'CVC 16028(a)',   title: 'Kein Versicherungsnachweis',                         cls: 'I', fine: 500,  jail: 0,  points: 0 },
      { code: 'CVC 5200(a)',    title: 'Kennzeichen fehlt / nicht sichtbar',                 cls: 'I', fine: 200,  jail: 0,  points: 0 },
      { code: 'CVC 26708(a)',   title: 'Unzulässige Scheibentönung',                         cls: 'I', fine: 200,  jail: 0,  points: 0 },
      { code: 'CVC 24250',      title: 'Fahren ohne Licht bei Dunkelheit',                   cls: 'I', fine: 150,  jail: 0,  points: 0 },
      { code: 'CVC 27150(a)',   title: 'Unzulässige / zu laute Auspuffanlage',               cls: 'I', fine: 250,  jail: 0,  points: 0 },
      { code: 'CVC 24002(a)',   title: 'Fahrzeug nicht verkehrssicher',                      cls: 'I', fine: 300,  jail: 0,  points: 0 },
      { code: 'CVC 27606',      title: 'Unerlaubte Blaulicht-/Sirenenanlage',                cls: 'M', fine: 1500, jail: 5,  points: 0 },
      { code: 'CVC 10851(a)',   title: 'Fahrzeugdiebstahl / unbefugte Benutzung',            cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'CVC 10852',      title: 'Manipulation / Beschädigung eines Fahrzeugs',        cls: 'M', fine: 1000, jail: 5,  points: 0 },
    ]
  },
  {
    id: 'dui', icon: '🍺', name: 'Alkohol, Unfall & Flucht (CVC)', items: [
      { code: 'CVC 23152(a)',   title: 'Fahren unter Alkohol-/Drogeneinfluss (DUI)',         cls: 'M', fine: 3000, jail: 15, points: 2, license: true },
      { code: 'CVC 23152(b)',   title: 'DUI mit 0,08 % BAK oder mehr',                       cls: 'M', fine: 3000, jail: 15, points: 2, license: true },
      { code: 'CVC 23153(a)',   title: 'DUI mit Personenschaden',                            cls: 'F', fine: 8000, jail: 40, points: 2, license: true },
      { code: 'CVC 23222(a)',   title: 'Offener Alkoholbehälter im Fahrzeug',                cls: 'I', fine: 250,  jail: 0,  points: 0 },
      { code: 'CVC 20002(a)',   title: 'Fahrerflucht (Sachschaden)',                         cls: 'M', fine: 2000, jail: 10, points: 2 },
      { code: 'CVC 20001(a)',   title: 'Fahrerflucht (Personenschaden)',                     cls: 'F', fine: 6000, jail: 30, points: 2, license: true },
      { code: 'CVC 2800.1(a)',  title: 'Flucht vor der Polizei (Evading)',                   cls: 'M', fine: 3000, jail: 15, points: 2 },
      { code: 'CVC 2800.2(a)',  title: 'Flucht vor der Polizei mit rücksichtsloser Fahrweise', cls: 'F', fine: 6000, jail: 30, points: 2, license: true },
      { code: 'CVC 2800.3(a)',  title: 'Flucht vor der Polizei mit Personenschaden',         cls: 'F', fine: 9000, jail: 45, points: 2, license: true },
    ]
  },
  {
    id: 'persons', icon: '👤', name: 'Straftaten gegen Personen (PC)', items: [
      { code: 'PC 187(a)', title: 'Mord', cls: 'F', fine: 30000, jail: 120, points: 0 },
      { code: 'PC 664/187(a)', title: 'Versuchter Mord', cls: 'F', fine: 20000, jail: 90, points: 0 },
      { code: 'PC 192(a)', title: 'Totschlag (Voluntary Manslaughter)', cls: 'F', fine: 15000, jail: 80, points: 0 },
      { code: 'PC 192(b)', title: 'Fahrlässige Tötung (Involuntary Manslaughter)', cls: 'F', fine: 10000, jail: 50, points: 0 },
      { code: 'PC 192(c)(1)', title: 'Fahrlässige Tötung mit Fahrzeug', cls: 'F', fine: 12000, jail: 60, points: 2, license: true },
      { code: 'PC 191.5(a)', title: 'Fahrlässige Tötung mit Fahrzeug unter Alkoholeinfluss', cls: 'F', fine: 18000, jail: 90, points: 2, license: true },
      { code: 'PC 203', title: 'Schwere Körperverletzung / Verstümmelung (Mayhem)', cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'PC 205', title: 'Schwere Verstümmelung (Aggravated Mayhem)', cls: 'F', fine: 18000, jail: 90, points: 0 },
      { code: 'PC 206', title: 'Folter', cls: 'F', fine: 20000, jail: 100, points: 0 },
      { code: 'PC 207(a)', title: 'Entführung (Kidnapping)', cls: 'F', fine: 15000, jail: 70, points: 0 },
      { code: 'PC 209(a)', title: 'Entführung mit Lösegeldforderung', cls: 'F', fine: 25000, jail: 110, points: 0 },
      { code: 'PC 209.5(a)', title: 'Entführung bei einem Fahrzeugraub', cls: 'F', fine: 22000, jail: 100, points: 0 },
      { code: 'PC 210.5', title: 'Geiselnahme (Freiheitsberaubung mit Schutzschild)', cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'PC 236', title: 'Freiheitsberaubung (False Imprisonment)', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 236.1(a)', title: 'Menschenhandel', cls: 'F', fine: 20000, jail: 100, points: 0 },
      { code: 'PC 240', title: 'Tätlicher Angriff (Assault)', cls: 'M', fine: 1500, jail: 10, points: 0 },
      { code: 'PC 241(c)', title: 'Tätlicher Angriff auf einen Beamten', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 242', title: 'Körperverletzung (Battery)', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 243(b)', title: 'Körperverletzung an einem Beamten', cls: 'M', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 243(c)(2)', title: 'Körperverletzung an einem Beamten mit Verletzung', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 243(d)', title: 'Schwere Körperverletzung (Serious Bodily Injury)', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 243(e)(1)', title: 'Körperverletzung an (Ex-)Partner', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 245(a)(1)', title: 'Angriff mit tödlicher Waffe (ADW)', cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'PC 245(a)(2)', title: 'Angriff mit einer Schusswaffe', cls: 'F', fine: 10000, jail: 50, points: 0 },
      { code: 'PC 245(a)(4)', title: 'Angriff mit potenziell schwer verletzender Gewalt', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 245(c)', title: 'Angriff mit tödlicher Waffe auf einen Beamten', cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'PC 245(d)(1)', title: 'Angriff mit Schusswaffe auf einen Beamten', cls: 'F', fine: 15000, jail: 75, points: 0 },
      { code: 'PC 246', title: 'Schießen auf bewohntes Gebäude / Fahrzeug', cls: 'F', fine: 10000, jail: 50, points: 0 },
      { code: 'PC 246.3(a)', title: 'Fahrlässiges Abfeuern einer Schusswaffe', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 247(b)', title: 'Schießen auf unbewohntes Gebäude / Fahrzeug', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 26100(c)', title: 'Schießen aus einem Fahrzeug (Drive-By)', cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'PC 273.5(a)', title: 'Häusliche Gewalt mit Verletzung', cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'PC 273a(a)', title: 'Gefährdung eines Kindes', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 273d(a)', title: 'Kindesmisshandlung', cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'PC 368(b)(1)', title: 'Misshandlung älterer / abhängiger Personen', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 422', title: 'Ernsthafte Bedrohung (Criminal Threats)', cls: 'F', fine: 2500, jail: 15, points: 0 },
      { code: 'PC 646.9(a)', title: 'Stalking', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 653m(a)', title: 'Belästigende / bedrohende Anrufe', cls: 'M', fine: 750, jail: 0, points: 0 },
    ]
  },
  {
    id: 'sexual', icon: '🚫', name: 'Sexualdelikte (PC)', items: [
      { code: 'PC 261(a)(2)', title: 'Vergewaltigung', cls: 'F', fine: 25000, jail: 110, points: 0 },
      { code: 'PC 243.4(a)', title: 'Sexuelle Nötigung (Sexual Battery)', cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'PC 314(1)', title: 'Exhibitionismus (Indecent Exposure)', cls: 'M', fine: 1500, jail: 5, points: 0 },
      { code: 'PC 647(j)(1)', title: 'Voyeurismus', cls: 'M', fine: 1500, jail: 5, points: 0 },
      { code: 'PC 647(b)(1)', title: 'Prostitution', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 266h(a)', title: 'Zuhälterei (Pimping)', cls: 'F', fine: 8000, jail: 35, points: 0 },
      { code: 'PC 266i(a)', title: 'Anwerbung zur Prostitution (Pandering)', cls: 'F', fine: 8000, jail: 35, points: 0 },
    ]
  },
  {
    id: 'property', icon: '💰', name: 'Eigentums- & Vermögensdelikte (PC)', items: [
      { code: 'PC 211', title: 'Raub (Robbery)', cls: 'F', fine: 7500, jail: 35, points: 0 },
      { code: 'PC 215(a)', title: 'Fahrzeugraub (Carjacking)', cls: 'F', fine: 9000, jail: 45, points: 0 },
      { code: 'PC 459/460(a)', title: 'Wohnungseinbruch (1st Degree Burglary)', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 459/460(b)', title: 'Einbruch in Gewerbe / Fahrzeug (2nd Degree)', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 459.5', title: 'Ladendiebstahl (Shoplifting, bis $950)', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 466', title: 'Besitz von Einbruchswerkzeug', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 484(a)', title: 'Diebstahl', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 488', title: 'Einfacher Diebstahl (Petty Theft)', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 487(a)', title: 'Schwerer Diebstahl (über $950)', cls: 'F', fine: 3500, jail: 20, points: 0 },
      { code: 'PC 487(c)', title: 'Diebstahl direkt von einer Person', cls: 'F', fine: 3500, jail: 20, points: 0 },
      { code: 'PC 487(d)(1)', title: 'Schwerer Diebstahl eines Fahrzeugs', cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'PC 496(a)', title: 'Hehlerei (Besitz gestohlener Ware)', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 496d(a)', title: 'Hehlerei mit gestohlenen Fahrzeugen', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 503', title: 'Unterschlagung (Embezzlement)', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 518', title: 'Erpressung', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 524', title: 'Versuchte Erpressung', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 470(a)', title: 'Urkundenfälschung', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 475(a)', title: 'Besitz gefälschter Dokumente / Banknoten', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 476', title: 'Ungedeckte / gefälschte Schecks', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 484e(d)', title: 'Diebstahl von Kreditkartendaten', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 484g', title: 'Kreditkartenbetrug', cls: 'F', fine: 3500, jail: 15, points: 0 },
      { code: 'PC 530.5(a)', title: 'Identitätsdiebstahl', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 532(a)', title: 'Betrug (False Pretenses)', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 537(a)', title: 'Zechprellerei / Hotelbetrug', cls: 'M', fine: 500, jail: 0, points: 0 },
      { code: 'PC 550(a)', title: 'Versicherungsbetrug', cls: 'F', fine: 6000, jail: 25, points: 0 },
      { code: 'PC 502(c)', title: 'Computerkriminalität / Hacking', cls: 'F', fine: 5000, jail: 20, points: 0 },
      { code: 'PC 594(a)', title: 'Sachbeschädigung / Vandalismus (unter $400)', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 594(b)(1)', title: 'Sachbeschädigung (ab $400)', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 594.3(a)', title: 'Beschädigung einer Kirche / Gedenkstätte', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 451(a)', title: 'Brandstiftung mit schwerer Körperverletzung', cls: 'F', fine: 15000, jail: 70, points: 0 },
      { code: 'PC 451(b)', title: 'Brandstiftung an bewohntem Gebäude', cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'PC 451(d)', title: 'Brandstiftung (Eigentum)', cls: 'F', fine: 8000, jail: 35, points: 0 },
      { code: 'PC 452(d)', title: 'Fahrlässige Brandverursachung', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 602', title: 'Hausfriedensbruch / unbefugtes Betreten', cls: 'M', fine: 750, jail: 5, points: 0 },
      { code: 'PC 602.5(a)', title: 'Unbefugtes Betreten einer Wohnung', cls: 'M', fine: 1500, jail: 5, points: 0 },
      { code: 'PC 597(a)', title: 'Tierquälerei', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 597.5(a)', title: 'Organisierte Hundekämpfe', cls: 'F', fine: 5000, jail: 25, points: 0 },
    ]
  },
  {
    id: 'justice', icon: '🏛️', name: 'Delikte gegen Staat & Justiz (PC)', items: [
      { code: 'PC 67', title: 'Bestechung eines Beamten', cls: 'F', fine: 7500, jail: 25, points: 0 },
      { code: 'PC 68(a)', title: 'Bestechlichkeit (Beamter nimmt Bestechung an)', cls: 'F', fine: 10000, jail: 40, points: 0 },
      { code: 'PC 69', title: 'Widerstand gegen Vollstreckungsbeamte (Gewalt/Drohung)', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 71', title: 'Bedrohung eines Amtsträgers', cls: 'F', fine: 3500, jail: 15, points: 0 },
      { code: 'PC 92', title: 'Bestechung eines Richters / Geschworenen', cls: 'F', fine: 10000, jail: 40, points: 0 },
      { code: 'PC 118(a)', title: 'Meineid (Perjury)', cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'PC 127', title: 'Anstiftung zum Meineid', cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'PC 132', title: 'Vorlage gefälschter Beweise', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 135', title: 'Vernichtung von Beweismitteln', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 136.1(a)', title: 'Einschüchterung von Zeugen / Opfern', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 137(b)', title: 'Zeugenbeeinflussung durch Gewalt / Drohung', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 141(a)', title: 'Unterschieben von Beweisen', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 148(a)(1)', title: 'Widerstand / Behinderung eines Beamten', cls: 'M', fine: 1500, jail: 10, points: 0 },
      { code: 'PC 148(c)', title: 'Entwenden der Dienstwaffe eines Beamten', cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'PC 148.1(a)', title: 'Falsche Bombendrohung', cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: 'PC 148.3(a)', title: 'Falscher Notruf (Swatting)', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 148.5(a)', title: 'Falschanzeige', cls: 'M', fine: 1500, jail: 5, points: 0 },
      { code: 'PC 148.9(a)', title: 'Falsche Identität gegenüber Beamten', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 148.10(a)', title: 'Widerstand mit Todesfolge / schwerer Verletzung eines Beamten', cls: 'F', fine: 15000, jail: 70, points: 0 },
      { code: 'PC 146a(a)', title: 'Vortäuschen eines Ermittlers / Beamten zur Täuschung', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 538d(a)', title: 'Amtsanmaßung (Vortäuschen Polizeibeamter)', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 166(a)(4)', title: 'Missachtung einer gerichtlichen Anordnung', cls: 'M', fine: 1500, jail: 10, points: 0 },
      { code: 'PC 166(c)(1)', title: 'Verstoß gegen Schutzanordnung (Restraining Order)', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 182(a)(1)', title: 'Verabredung zu einer Straftat (Conspiracy)', cls: 'F', fine: 5000, jail: 20, points: 0 },
      { code: 'PC 32', title: 'Beihilfe nach der Tat (Accessory)', cls: 'F', fine: 2500, jail: 15, points: 0 },
      { code: 'PC 186.22(a)', title: 'Beteiligung an krimineller Straßengang', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 853.7', title: 'Nichterscheinen trotz Vorladung (FTA)', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 1320(b)', title: 'Nichterscheinen nach Freilassung (Felony)', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 1320.5', title: 'Nichterscheinen trotz Kaution (Bail Jumping)', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 4530(a)', title: 'Ausbruch aus dem Staatsgefängnis', cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'PC 4532(b)(1)', title: 'Ausbruch aus dem County-Gefängnis', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 4573(a)', title: 'Schmuggel von Drogen ins Gefängnis', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 4574(a)', title: 'Schmuggel von Waffen ins Gefängnis', cls: 'F', fine: 8000, jail: 35, points: 0 },
      { code: 'PC 4600(a)', title: 'Beschädigung von Gefängniseigentum', cls: 'M', fine: 2000, jail: 10, points: 0 },
    ]
  },
  {
    id: 'order', icon: '📢', name: 'Öffentliche Ordnung (PC)', items: [
      { code: 'PC 404.6(a)', title: 'Anstiftung zum Aufruhr (Riot)', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 405', title: 'Teilnahme an einem Aufruhr', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 409', title: 'Verbleiben bei einer aufgelösten Versammlung', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 415(1)', title: 'Schlägerei in der Öffentlichkeit', cls: 'M', fine: 750, jail: 5, points: 0 },
      { code: 'PC 415(2)', title: 'Ruhestörung durch Lärm', cls: 'M', fine: 300, jail: 0, points: 0 },
      { code: 'PC 415(3)', title: 'Beleidigende Worte in der Öffentlichkeit', cls: 'M', fine: 300, jail: 0, points: 0 },
      { code: 'PC 647(e)', title: 'Unerlaubtes Übernachten / Lagern', cls: 'M', fine: 300, jail: 0, points: 0 },
      { code: 'PC 647(f)', title: 'Öffentliche Trunkenheit', cls: 'M', fine: 300, jail: 0, points: 0 },
      { code: 'PC 647(h)', title: 'Herumlungern mit Diebstahlabsicht', cls: 'M', fine: 500, jail: 0, points: 0 },
      { code: 'PC 370/372', title: 'Öffentliches Ärgernis (Public Nuisance)', cls: 'M', fine: 500, jail: 0, points: 0 },
      { code: 'PC 374.3(a)', title: 'Illegale Müllentsorgung', cls: 'I', fine: 500, jail: 0, points: 0 },
      { code: 'PC 640(b)', title: 'Schwarzfahren (Fare Evasion)', cls: 'I', fine: 150, jail: 0, points: 0 },
      { code: 'PC 330', title: 'Illegales Glücksspiel', cls: 'M', fine: 1000, jail: 0, points: 0 },
      { code: 'PC 337a', title: 'Illegale Sportwetten (Bookmaking)', cls: 'M', fine: 2500, jail: 10, points: 0 },
    ]
  },
  {
    id: 'weapons', icon: '🔫', name: 'Waffen & Sprengstoff (PC)', items: [
      { code: 'PC 417(a)(2)', title: 'Bedrohen mit einer Schusswaffe (Brandishing)', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 417(c)', title: 'Bedrohen eines Beamten mit einer Schusswaffe', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 417.4', title: 'Bedrohen mit einer Waffen-Attrappe', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 25400(a)', title: 'Verdecktes Tragen einer Schusswaffe ohne Lizenz', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 25850(a)', title: 'Geladene Schusswaffe in der Öffentlichkeit', cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 26350(a)', title: 'Offenes Tragen einer Faustfeuerwaffe', cls: 'M', fine: 1500, jail: 5, points: 0 },
      { code: 'PC 26500', title: 'Waffenverkauf ohne Händlerlizenz', cls: 'M', fine: 4000, jail: 15, points: 0 },
      { code: 'PC 27500(a)', title: 'Waffenverkauf an verbotene Person', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 29800(a)', title: 'Waffenbesitz als vorbestrafte Person (Felon)', cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'PC 30305(a)', title: 'Munitionsbesitz als verbotene Person', cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: 'PC 30605(a)', title: 'Besitz einer Sturmwaffe (Assault Weapon)', cls: 'F', fine: 8000, jail: 35, points: 0 },
      { code: 'PC 32625(a)', title: 'Besitz eines Maschinengewehrs (vollautomatisch)', cls: 'F', fine: 12000, jail: 50, points: 0 },
      { code: 'PC 33215', title: 'Kurzläufiges Gewehr / Schrotflinte', cls: 'F', fine: 5000, jail: 20, points: 0 },
      { code: 'PC 33410', title: 'Besitz eines Schalldämpfers', cls: 'F', fine: 5000, jail: 20, points: 0 },
      { code: 'PC 32310(a)', title: 'Herstellung / Verkauf von Großmagazinen', cls: 'M', fine: 3000, jail: 10, points: 0 },
      { code: 'PC 23900', title: 'Entfernte / unkenntliche Seriennummer', cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: 'PC 17500', title: 'Besitz einer tödlichen Waffe mit Angriffsabsicht', cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'PC 21310', title: 'Verdecktes Tragen eines Dolches / Messers', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 21510', title: 'Besitz / Tragen eines Springmessers', cls: 'M', fine: 750, jail: 0, points: 0 },
      { code: 'PC 21810', title: 'Besitz eines Schlagrings', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 22210', title: 'Besitz eines Totschlägers / Schlagstocks', cls: 'M', fine: 1000, jail: 5, points: 0 },
      { code: 'PC 626.10(a)', title: 'Waffen auf Schulgelände', cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'PC 18710(a)', title: 'Besitz eines Sprengsatzes', cls: 'F', fine: 10000, jail: 45, points: 0 },
      { code: 'PC 18720', title: 'Sprengsatz mit Absicht zu Schaden', cls: 'F', fine: 15000, jail: 70, points: 0 },
      { code: 'PC 18740', title: 'Zünden eines Sprengsatzes mit Verletzungsabsicht', cls: 'F', fine: 20000, jail: 100, points: 0 },
    ]
  },
  {
    id: 'drugs', icon: '💊', name: 'Betäubungsmittel (Health & Safety Code)', items: [
      { code: 'HS 11357(b)',    title: 'Cannabis-Besitz über der erlaubten Menge (28,5 g)',  cls: 'M', fine: 500,  jail: 0,  points: 0 },
      { code: 'HS 11359(b)',    title: 'Besitz von Cannabis zum Verkauf',                    cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: 'HS 11358',       title: 'Illegaler Cannabis-Anbau',                           cls: 'M', fine: 3000, jail: 10, points: 0 },
      { code: 'HS 11350(a)',    title: 'Besitz einer kontrollierten Substanz',               cls: 'M', fine: 1500, jail: 10, points: 0 },
      { code: 'HS 11377(a)',    title: 'Besitz von Methamphetamin',                          cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: 'HS 11351',       title: 'Besitz kontrollierter Substanzen zum Verkauf',       cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'HS 11378',       title: 'Besitz von Methamphetamin zum Verkauf',              cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: 'HS 11352(a)',    title: 'Transport / Verkauf kontrollierter Substanzen',      cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: 'HS 11379.6',     title: 'Herstellung von Drogen (Drogenlabor)',               cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: 'HS 11364',       title: 'Besitz von Drogenutensilien',                        cls: 'M', fine: 300,  jail: 0,  points: 0 },
      { code: 'HS 11550(a)',    title: 'Unter Einfluss kontrollierter Substanzen',           cls: 'M', fine: 1000, jail: 5,  points: 0 },
    ]
  },
  {
    id: 'federal', icon: '🦅', name: 'Bundesrecht (U.S. Code)', items: [
      { code: '18 USC 111',     title: 'Angriff auf / Behinderung eines Bundesbeamten',      cls: 'F', fine: 8000, jail: 35, points: 0 },
      { code: '18 USC 912',     title: 'Amtsanmaßung (Vortäuschen Bundesbeamter)',           cls: 'F', fine: 5000, jail: 20, points: 0 },
      { code: '18 USC 1001',    title: 'Falschaussage gegenüber Bundesbehörden',             cls: 'F', fine: 4000, jail: 15, points: 0 },
      { code: '18 USC 1071',    title: 'Verstecken eines Flüchtigen (Harboring)',            cls: 'M', fine: 3000, jail: 15, points: 0 },
      { code: '18 USC 1073',    title: 'Flucht zur Vermeidung von Strafverfolgung',          cls: 'F', fine: 5000, jail: 25, points: 0 },
      { code: '18 USC 751',     title: 'Flucht aus dem Gewahrsam (Escape)',                  cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: '18 USC 3146',    title: 'Nichterscheinen trotz Kaution (Bail Jumping)',       cls: 'F', fine: 4000, jail: 20, points: 0 },
      { code: '18 USC 401',     title: 'Missachtung des Bundesgerichts (Contempt)',          cls: 'M', fine: 2000, jail: 10, points: 0 },
      { code: '18 USC 1503',    title: 'Behinderung der Justiz (Obstruction of Justice)',    cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: '18 USC 1512',    title: 'Zeugenbeeinflussung (Witness Tampering)',            cls: 'F', fine: 8000, jail: 40, points: 0 },
      { code: '18 USC 1201',    title: 'Entführung (Bundesrecht)',                           cls: 'F', fine: 15000, jail: 80, points: 0 },
      { code: '18 USC 922(g)',  title: 'Waffenbesitz trotz Verbot (z.B. vorbestraft)',       cls: 'F', fine: 6000, jail: 30, points: 0 },
      { code: '18 USC 1361',    title: 'Beschädigung von Bundeseigentum',                    cls: 'M', fine: 2500, jail: 10, points: 0 },
      { code: '18 USC 1708',    title: 'Postdiebstahl',                                      cls: 'F', fine: 3000, jail: 15, points: 0 },
      { code: '18 USC 2113(a)', title: 'Bankraub',                                           cls: 'F', fine: 15000, jail: 70, points: 0 },
      { code: '18 USC 2119',    title: 'Fahrzeugraub (Bundesrecht)',                         cls: 'F', fine: 10000, jail: 50, points: 0 },
      { code: '21 USC 841(a)',  title: 'Drogenhandel (Bundesrecht)',                         cls: 'F', fine: 12000, jail: 60, points: 0 },
      { code: '18 USC 1956',    title: 'Geldwäsche',                                         cls: 'F', fine: 10000, jail: 45, points: 0 },
    ]
  },
];
